name: Playwright Tests with Allure Reports

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run test

      # Generate and save Allure results
      - name: Prepare Allure Report
        run: |
          npx allure-commandline generate ./allure-results --clean -o ./allure-report
        if: success() || failure()
        
      - name: Debug Allure Report Directory
        if: always()
        run: ls -l ./allure-report

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true  # Ensures that files aren't overwritten, maintaining history