name: Playwright Tests with Allure Reports

on:
  workflow_dispatch: # Manually trigger the workflow
    inputs:
      mission_id:
        description: 'Mission ID'     
        required: true
        default: '0'
      inclusions:
        description: 'Product inclusions'  
        required: true
      exclusions:
        description: 'Product exclusions'
        required: true

jobs:
  allocate_mission:
    name: Allocate Mission
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean and install dependencies
        run: npm ci
      
      # Step for mission allocation logic

      # - name: Run ESLint
      #   run: npx eslint . --max-warnings=0
  
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: allocate_mission  # Waits for the 'allocate_mission' job to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean and install dependencies
        run: npm ci

      - name: List test params
        run: |
          echo "Mission ID: ${{ github.event.inputs.mission_id }}"
          echo "Inclusions: ${{ github.event.inputs.inclusions }}"
          echo "Exclusions: ${{ github.event.inputs.exclusions }}"

      - name: Run Playwright tests
        run: npm run test

      - name: Save Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results
          retention-days: 1

  send_report:
    name: Send Report
    runs-on: ubuntu-latest
    needs: run_tests  # Waits for 'run_tests' job to finish
    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results

      # Add step to send test report

      # - name: Deploy Allure Report to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./allure-report
      #     keep_files: true  # Ensures history is maintained