name: Playwright Tests with Allure Reports

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Save Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules
          retention-days: 1  # Keep artifacts for 1 day

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build  # Waits for the 'build' job to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Node Modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Check Installed Packages
        run: npm list --depth=0

      - name: Run Playwright tests
        run: npm run test

      - name: Generate Allure Report
        run: |
          npx allure-commandline generate ./allure-results --clean -o ./allure-report
        if: success() || failure()

      - name: Save Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 1

  send_report:
    name: Send Report
    runs-on: ubuntu-latest
    needs: run_tests  # Waits for 'run_tests' job to finish
    steps:
      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true  # Ensures history is maintained